language: go
sudo: true
go:
 - 1.4
 - 1.5
 - 1.6
 - 1.7
 - tip
matrix:
 allow_failures:
   - go: tip
   - go: 1.4
   - go: 1.5
before_install:
 - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
 - sudo apt-get update
 - sudo apt-get install --force-yes libcv-dev libcvaux-dev libhighgui-dev libopencv-dev libusb-dev xvfb unzip libgtk2.0-0
 - mkdir -p sdl2
 - cd sdl2
 - "wget -q http://www.libsdl.org/release/SDL2-2.0.4.tar.gz"
 - tar xf SDL2-*.tar.gz
 - cd SDL2-* && ./configure --prefix=$SDL_PREFIX && make && sudo make install
 - cd ..
 - mkdir -p gnatsd
 - cd gnatsd
 - "wget https://github.com/nats-io/gnatsd/releases/download/v0.9.4/gnatsd-v0.9.4-linux-amd64.zip"
 - unzip -j gnatsd-v0.9.4-linux-amd64.zip
 - ./gnatsd -p 4222 &
 - ./gnatsd -p 4223 --user test --pass testwd &
 - cd $HOME/gopath/src/github.com/hybridgroup/gobot
 - go get github.com/axw/gocov/gocov
 - go get github.com/mattn/goveralls
 - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
install:
 - make deps
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script:
 - ./scripts/travis.sh
branches:
  except:
    - gobot.io
    - /^gobot-.*$/
